"""make constituency_id nullable

Revision ID: 3464b99e2898
Revises: d1c396852005
Create Date: 2026-03-22 19:42:03.929078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3464b99e2898'
down_revision: Union[str, None] = 'd1c396852005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'constituency_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaints', 'constituency_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
