"""add ai fields to complaints

Revision ID: 5a1b2c3d4e5f
Revises: 3464b99e2898
Create Date: 2026-03-23 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a1b2c3d4e5f'
down_revision: Union[str, None] = '3464b99e2898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('ai_overview', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('suggested_action', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('suggested_assignee_role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'suggested_assignee_role')
    op.drop_column('complaints', 'suggested_action')
    op.drop_column('complaints', 'ai_overview')
    # ### end Alembic commands ###